name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            repository: timheuer/SimpleFrameworkApp
            ref: master

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
            msbuid SimpleFrameworkApp.csproj
            msbuid SimpleFrameworkApp.sln
