name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            repository: timheuer/SimpleFrameworkApp
            ref: master
            
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Run a one-line script
        run: |
            echo Hello, world!
            whoami

      - name: Run a multi-line script
        run: |
            nuget restore SimpleFrameworkApp.sln
            nuget restore SimpleFrameworkApp.csproj
            msbuild SimpleFrameworkApp.csproj
            msbuild SimpleFrameworkApp.sln
